/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar novo usuário (apenas master) */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login com e-mail e senha */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout — limpa o cookie de autenticação */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna os dados do usuário autenticado */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trocar senha (obrigatório após primeiro login ou reset) */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar audit log. Master vê tudo (pode filtrar por companyId). Demais usuários veem apenas da própria empresa. */
        get: operations["AuditController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todas as empresas (apenas master) */
        get: operations["CompaniesController_findAll"];
        put?: never;
        /** Criar uma nova empresa + usuário admin inicial (apenas master). Retorna senha temporária. */
        post: operations["CompaniesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar empresa por ID (apenas master) */
        get: operations["CompaniesController_findOne"];
        put?: never;
        post?: never;
        /** Excluir empresa (apenas master). Bloqueado se houver condomínios ativos. */
        delete: operations["CompaniesController_remove"];
        options?: never;
        head?: never;
        /** Atualizar nome/CNPJ da empresa (apenas master) */
        patch: operations["CompaniesController_updateCompany"];
        trace?: never;
    };
    "/api/v1/companies/{companyId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar usuários de uma empresa (master ou gerente da empresa) */
        get: operations["CompaniesController_listUsers"];
        put?: never;
        /** Criar funcionário de uma empresa (master ou gerente da empresa). Sempre cria com role FUNCIONARIO. Retorna senha temporária. */
        post: operations["CompaniesController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{companyId}/condominiums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar condomínios de uma empresa (apenas master) */
        get: operations["CompaniesController_listCondominiums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{companyId}/users/{userId}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resetar senha de qualquer usuário da empresa (apenas master). Aceita admins e funcionários. */
        post: operations["CompaniesController_resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condominiums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar condomínios do usuário autenticado */
        get: operations["CondominiumsController_findAll"];
        put?: never;
        /**
         * Criar condomínio (master para qualquer empresa; gerente na sua)
         * @description MASTER cria para qualquer empresa (companyId no body, obrigatório). GERENTE cria apenas na própria empresa (companyId vem do token, o do body é ignorado). FUNCIONARIO não pode criar.
         */
        post: operations["CondominiumsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condominiums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar condomínio por ID */
        get: operations["CondominiumsController_findOne"];
        put?: never;
        post?: never;
        /** Remover condomínio (apenas master) */
        delete: operations["CondominiumsController_remove"];
        options?: never;
        head?: never;
        /** Atualizar condomínio (requer ADMIN) */
        patch: operations["CondominiumsController_update"];
        trace?: never;
    };
    "/api/v1/condominiums/{id}/regimento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download do PDF de regimento */
        get: operations["CondominiumsController_downloadRegimento"];
        put?: never;
        /** Upload do PDF de regimento (PDF, máx 5MB) */
        post: operations["CondominiumsController_uploadRegimento"];
        /** Remove o regimento cadastrado */
        delete: operations["CondominiumsController_removeRegimento"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condominiums/{condominiumId}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar unidades do condomínio */
        get: operations["UnitsController_findAll"];
        put?: never;
        /** Criar unidade no condomínio (GERENTE) */
        post: operations["UnitsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condominiums/{condominiumId}/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar unidade por ID */
        get: operations["UnitsController_findOne"];
        put?: never;
        post?: never;
        /** Remover unidade (GERENTE) */
        delete: operations["UnitsController_remove"];
        options?: never;
        head?: never;
        /** Atualizar unidade (GERENTE) */
        patch: operations["UnitsController_update"];
        trace?: never;
    };
    "/api/v1/infractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar infrações (filtrar por unidade, paginado) */
        get: operations["InfractionsController_findAll"];
        put?: never;
        /** Criar infração */
        post: operations["InfractionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar infrações em CSV (sem paginação) */
        get: operations["InfractionsController_exportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar infração por ID */
        get: operations["InfractionsController_findOne"];
        put?: never;
        post?: never;
        /** Remover infração */
        delete: operations["InfractionsController_remove"];
        options?: never;
        head?: never;
        /** Atualizar infração */
        patch: operations["InfractionsController_update"];
        trace?: never;
    };
    "/api/v1/infractions/{id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analisar infração via IA (Gemini) — limite: 10 req/min */
        post: operations["InfractionsController_analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download do documento PDF da infração */
        get: operations["InfractionsController_generateDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aprovar infração analisada (status analyzed → approved). Permite override opcional dos campos. */
        patch: operations["InfractionsController_approve"];
        trace?: never;
    };
    "/api/v1/infractions/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar infração aprovada por e-mail ao morador (status approved → sent). */
        post: operations["InfractionsController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}/send-whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar alerta por WhatsApp (canal complementar; não muda o status principal). */
        post: operations["InfractionsController_sendWhatsapp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/condominiums/{condominiumId}/infractions/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download do relatório PDF de infrações do condomínio (ADMIN ou MANAGER) */
        get: operations["ReportsController_getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar metadados das imagens da infração */
        get: operations["ImagesController_list"];
        put?: never;
        /** Upload de imagem da infração (JPEG, PNG ou WebP; máx 5MB; até 10 imagens) */
        post: operations["ImagesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download da imagem (binário) */
        get: operations["ImagesController_download"];
        put?: never;
        post?: never;
        /** Remover imagem da infração */
        delete: operations["ImagesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar notificações enviadas para a infração */
        get: operations["NotificationsController_findByInfraction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook do Resend para atualização de status */
        post: operations["WebhooksController_resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas gerais (master vê tudo; não-master filtrado por empresa) */
        get: operations["DashboardController_getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /** @example Maria Souza */
            nome: string;
            /** @example maria@email.com */
            email: string;
            /** @example S3nh@Segura */
            senha: string;
            /**
             * @example FUNCIONARIO
             * @enum {string}
             */
            role: "MASTER" | "GERENTE" | "FUNCIONARIO";
        };
        ProfileResponseDto: {
            nome: string;
            email: string;
            isMaster: boolean;
            companyId: number | null;
            mustChangePassword: boolean;
            companyName: string | null;
            /** @enum {string} */
            role: "MASTER" | "GERENTE" | "FUNCIONARIO";
        };
        ChangePasswordDto: {
            /** @example NovaSenha@2026 */
            newPassword: string;
        };
        CreateCompanyAdminDto: {
            nome: string;
            email: string;
        };
        CreateCompanyDto: {
            /** @example Administradora Exemplo Ltda */
            name: string;
            /** @example 12.345.678/0001-90 */
            cnpj: string;
            admin: components["schemas"]["CreateCompanyAdminDto"];
        };
        CompanyResponseDto: {
            id: number;
            name: string;
            cnpj: string;
            /** Format: date-time */
            createdAt: string;
        };
        CompanyUserResponseDto: {
            id: number;
            nome: string;
            email: string;
            /** @enum {string} */
            role: "MASTER" | "GERENTE" | "FUNCIONARIO";
        };
        UpdateCompanyDto: {
            /** @example Nova Administradora Ltda */
            name?: string;
            /** @example 12.345.678/0001-90 */
            cnpj?: string;
        };
        CreateEmployeeDto: {
            nome: string;
            email: string;
        };
        CreatedEmployeeResponseDto: {
            id: number;
            nome: string;
            email: string;
            /** @description Senha temporária gerada (mostrar uma única vez). */
            tempPassword: string;
        };
        CreateCondominiumDto: {
            /**
             * @description ID da empresa dona do condomínio. Obrigatório para master; ignorado para gerente (usa sempre a própria empresa, do token).
             * @example 1
             */
            companyId?: number;
            /** @example Condomínio Jardim das Flores */
            name: string;
            /** @example 12345678000195 */
            cnpj: string;
            /** @example Rua das Acácias, 100 - São Paulo, SP */
            address: string;
        };
        CondominiumResponseDto: {
            id: number;
            name: string;
            cnpj: string;
            address: string;
            companyId: number;
            regimentoFilename: string | null;
            /** Format: date-time */
            regimentoUploadedAt: string | null;
            /** Format: date-time */
            deletedAt: string | null;
        };
        PaginatedCondominiumsDto: {
            data: components["schemas"]["CondominiumResponseDto"][];
            total: number;
            page: number;
            limit: number;
        };
        UpdateCondominiumDto: {
            /**
             * @description ID da empresa dona do condomínio. Obrigatório para master; ignorado para gerente (usa sempre a própria empresa, do token).
             * @example 1
             */
            companyId?: number;
            /** @example Condomínio Jardim das Flores */
            name?: string;
            /** @example 12345678000195 */
            cnpj?: string;
            /** @example Rua das Acácias, 100 - São Paulo, SP */
            address?: string;
        };
        CreateUnitDto: {
            /** @example A-101 */
            identifier: string;
            /** @example João da Silva */
            ownerName: string;
            /** @example morador@exemplo.com */
            residentEmail?: string;
            /** @example +5511999998888 */
            residentPhone?: string;
        };
        UnitResponseDto: {
            id: number;
            identifier: string;
            ownerName: string;
            residentEmail: string | null;
            residentPhone: string | null;
            /** Format: date-time */
            deletedAt: string | null;
        };
        PaginatedUnitsDto: {
            data: components["schemas"]["UnitResponseDto"][];
            total: number;
            page: number;
            limit: number;
        };
        UpdateUnitDto: {
            /** @example A-101 */
            identifier?: string;
            /** @example João da Silva */
            ownerName?: string;
            /** @example morador@exemplo.com */
            residentEmail?: string;
            /** @example +5511999998888 */
            residentPhone?: string;
        };
        CreateInfractionDto: {
            /** @example Morador toca som alto após 22h. */
            description: string;
            /**
             * @description Gravidade classificada pelo operador (obrigatória).
             * @example MEDIA
             * @enum {string}
             */
            severity: "LEVE" | "MEDIA" | "GRAVE";
            /** @example 1 */
            unitId: number;
        };
        InfractionResponseDto: {
            id: number;
            description: string;
            /** @enum {string} */
            severity: "LEVE" | "MEDIA" | "GRAVE";
            formalDescription: string | null;
            suggestedPenalty: string | null;
            /** @enum {string} */
            status: "pending" | "analyzed" | "approved" | "sent";
            /** Format: date-time */
            occurrenceDate: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            approvedAt: string | null;
            /** Format: date-time */
            sentAt: string | null;
            /** Format: date-time */
            whatsappSentAt: string | null;
            /** Format: date-time */
            deletedAt: string | null;
        };
        PaginatedInfractionsDto: {
            data: components["schemas"]["InfractionResponseDto"][];
            total: number;
            page: number;
            limit: number;
        };
        ApproveInfractionDto: {
            /** @description Optional override of the AI-generated formal description before approval. */
            formalDescription?: string;
            /** @description Optional override of the AI-suggested penalty before approval. */
            suggestedPenalty?: string;
        };
        UpdateInfractionDto: {
            /** @example Morador toca som alto após 22h. */
            description?: string;
            /**
             * @description Gravidade classificada pelo operador (obrigatória).
             * @example MEDIA
             * @enum {string}
             */
            severity?: "LEVE" | "MEDIA" | "GRAVE";
            /** @example 1 */
            unitId?: number;
        };
        ByMonthItemDto: {
            month: string;
            count: number;
        };
        TopUnitItemDto: {
            unitId: number;
            identifier: string;
            condominiumName: string;
            count: number;
        };
        DashboardResponseDto: {
            totalInfractions: number;
            /** @description Contagem por status (pending, analyzed, approved, sent) */
            byStatus: {
                [key: string]: number;
            };
            byMonth: components["schemas"]["ByMonthItemDto"][];
            topUnits: components["schemas"]["TopUnitItemDto"][];
            approvalRate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Usuário criado (senha omitida na resposta) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requer usuário master */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail já cadastrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example maria@email.com */
                    email: string;
                    /** @example S3nh@Segura */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login bem-sucedido. Seta o cookie httpOnly access_token; corpo apenas { success: true }. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie de autenticação removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token inválido ou ausente */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
            /** @description Token inválido ou ausente */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Senha alterada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Senha inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token inválido ou ausente */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtro de empresa (apenas master) */
                companyId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de empresas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponseDto"][];
                };
            };
        };
    };
    CompaniesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyDto"];
            };
        };
        responses: {
            /** @description Empresa criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponseDto"];
                };
            };
            /** @description Apenas master pode criar empresas */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CNPJ ou e-mail já cadastrados */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empresa encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponseDto"];
                };
            };
            /** @description Empresa não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empresa removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empresa não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empresa possui condomínios ativos */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_updateCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompanyDto"];
            };
        };
        responses: {
            /** @description Empresa atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponseDto"];
                };
            };
            /** @description Empresa não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CNPJ já cadastrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de usuários da empresa (inclui role) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyUserResponseDto"][];
                };
            };
            /** @description Papel ou empresa sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empresa não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            /** @description Funcionário criado (role FUNCIONARIO) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedEmployeeResponseDto"];
                };
            };
            /** @description Papel ou empresa sem permissão */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empresa não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail já cadastrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_listCondominiums: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de condomínios da empresa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: number;
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Senha resetada, retorna senha temporária */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não pertence à empresa */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de condomínios do usuário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCondominiumsDto"];
                };
            };
        };
    };
    CondominiumsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCondominiumDto"];
            };
        };
        responses: {
            /** @description Condomínio criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondominiumResponseDto"];
                };
            };
            /** @description companyId ausente (master) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Papel sem permissão (funcionário) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CNPJ já cadastrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Condomínio encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondominiumResponseDto"];
                };
            };
            /** @description Sem acesso a este condomínio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Condomínio não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Condomínio removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Apenas master pode remover */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCondominiumDto"];
            };
        };
        responses: {
            /** @description Condomínio atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondominiumResponseDto"];
                };
            };
            /** @description Apenas ADMIN pode editar */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_downloadRegimento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF retornado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Regimento não cadastrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_uploadRegimento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Regimento salvo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo inválido ou ausente */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CondominiumsController_removeRegimento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regimento removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominiumId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de unidades */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUnitsDto"];
                };
            };
        };
    };
    UnitsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condominiumId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitDto"];
            };
        };
        responses: {
            /** @description Unidade criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitResponseDto"];
                };
            };
        };
    };
    UnitsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                condominiumId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unidade encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitResponseDto"];
                };
            };
        };
    };
    UnitsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                condominiumId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unidade removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UnitsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                condominiumId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitDto"];
            };
        };
        responses: {
            /** @description Unidade atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitResponseDto"];
                };
            };
        };
    };
    InfractionsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtrar por unidade */
                unitId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de infrações */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInfractionsDto"];
                };
            };
        };
    };
    InfractionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInfractionDto"];
            };
        };
        responses: {
            /** @description Infração criada com status pending */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
        };
    };
    InfractionsController_exportCsv: {
        parameters: {
            query?: {
                /** @description Filtrar por unidade */
                unitId?: number;
                status?: "pending" | "analyzed" | "approved" | "sent";
                /** @description Data início (ISO 8601) */
                from?: string;
                /** @description Data fim (ISO 8601) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
        };
    };
    InfractionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infração encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
            /** @description Infração não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InfractionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infração removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InfractionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInfractionDto"];
            };
        };
        responses: {
            /** @description Infração atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
        };
    };
    InfractionsController_analyze: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infração analisada, status → analyzed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
            /** @description Muitas requisições — aguarde antes de tentar novamente */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro na API Gemini */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InfractionsController_generateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF gerado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
        };
    };
    InfractionsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveInfractionDto"];
            };
        };
        responses: {
            /** @description Infração aprovada, status → approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
            /** @description Infração não está no status analyzed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Infração não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InfractionsController_send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description E-mail enviado, status → sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
            /** @description Infração não está no status approved ou unidade sem e-mail cadastrado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Infração não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InfractionsController_sendWhatsapp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WhatsApp enviado, whatsappSentAt preenchido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfractionResponseDto"];
                };
            };
            /** @description Status diferente de approved/sent ou unidade sem telefone */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Infração não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getReport: {
        parameters: {
            query?: {
                /** @description Data inicial (ISO 8601) */
                from?: string;
                /** @description Data final (ISO 8601) */
                to?: string;
            };
            header?: never;
            path: {
                condominiumId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF gerado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Sem permissão (requer ADMIN ou MANAGER) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de metadados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Imagem salva */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo inválido, MIME não suportado ou limite excedido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Infração não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                imageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imagem retornada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Imagem não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImagesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                imageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imagem removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Imagem não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_findByInfraction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de notificações com status real */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_resend: {
        parameters: {
            query?: never;
            header: {
                "svix-signature": string;
                "svix-timestamp": string;
                "svix-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas do dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
}
